/**
 * quizData.js — All 15 quiz questions for the fence quiz.
 */

export const QUESTIONS = [
  // ── Block 1: Visual / Product (Q1-Q4) ─────────────────────────────
  {
    id: 'q1',
    block: 'visual',
    blockLabel: 'Your Fence Vision',
    question: "What's the main purpose of your fence?",
    hint: 'Select all that apply.',
    multiSelect: true,
    options: [
      { value: 'security',       label: 'Security',          icon: 'shield' },
      { value: 'privacy',        label: 'Privacy',           icon: 'eye-off' },
      { value: 'curb_appeal',    label: 'Curb Appeal',       icon: 'sparkles' },
      { value: 'pool_safety',    label: 'Pool Safety',       icon: 'waves' },
      { value: 'pet_containment', label: 'Pet Containment',  icon: 'paw' },
      { value: 'hoa_code',       label: 'HOA / Code Req.',   icon: 'clipboard' },
    ],
  },
  {
    id: 'q2',
    block: 'visual',
    blockLabel: 'Your Fence Vision',
    question: 'Which style catches your eye?',
    hint: 'Pick the one that appeals to you most.',
    multiSelect: false,
    options: [
      { value: 'flat_top',        label: 'Flat Top'          },
      { value: 'spear_top',       label: 'Spear Top'         },
      { value: 'decorative',      label: 'Decorative'        },
      { value: 'privacy_screen',  label: 'Privacy Screen'    },
      { value: 'high_security',   label: 'High Security'     },
      { value: 'not_sure',        label: "Not Sure Yet"      },
    ],
  },
  {
    id: 'q3',
    block: 'visual',
    blockLabel: 'Your Fence Vision',
    question: 'What type of property is this for?',
    hint: 'This helps us recommend the right product line.',
    multiSelect: false,
    options: [
      { value: 'single_family',   label: 'Single Family Home' },
      { value: 'multi_family',    label: 'Multi-Family / HOA' },
      { value: 'commercial',      label: 'Commercial'         },
      { value: 'industrial_gov',  label: 'Industrial / Gov.'  },
      { value: 'rental',          label: 'Rental Property'    },
    ],
  },
  {
    id: 'q4',
    block: 'visual',
    blockLabel: 'Your Fence Vision',
    question: 'Any special conditions on your property?',
    hint: 'Select all that apply.',
    multiSelect: true,
    options: [
      { value: 'sloped',    label: 'Sloped / Hilly Terrain' },
      { value: 'coastal',   label: 'Coastal / Salt Air'     },
      { value: 'high_wind', label: 'High Wind Area'         },
      { value: 'near_pool', label: 'Near a Pool'            },
      { value: 'hoa',       label: 'HOA Restrictions'       },
      { value: 'none',      label: 'None of These'          },
    ],
  },

  // ── Block 2: Readiness Score (Q5-Q10) ──────────────────────────────
  {
    id: 'q5',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Do you know your property lines/boundaries?',
    hint: 'Knowing your boundaries prevents costly mistakes.',
    multiSelect: false,
    options: [
      { value: 'yes_surveyed', label: 'Yes, surveyed',            points: 17 },
      { value: 'think_so',    label: 'I think so',                points: 8  },
      { value: 'no',          label: 'No',                        points: 0  },
      { value: 'not_sure',    label: "Not sure",                  points: 0  },
    ],
  },
  {
    id: 'q6',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Have you checked local codes and permit requirements?',
    hint: 'Many areas require permits for fence installation.',
    multiSelect: false,
    options: [
      { value: 'yes',        label: 'Yes',                        points: 17 },
      { value: 'looked',     label: "I've looked into it",        points: 8  },
      { value: 'no',         label: 'No',                         points: 0  },
      { value: 'didnt_know', label: "Didn't know I needed to",    points: 0  },
    ],
  },
  {
    id: 'q7',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Do you have a timeline for your fence project?',
    hint: 'This helps us gauge how quickly you need guidance.',
    multiSelect: false,
    options: [
      { value: '30_days',    label: 'Within 30 days',             points: 17 },
      { value: '1_3_months', label: '1-3 months',                 points: 8  },
      { value: '3_6_months', label: '3-6 months',                 points: 8  },
      { value: 'exploring',  label: 'Just exploring',             points: 0  },
    ],
  },
  {
    id: 'q8',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Have you compared fence materials?',
    hint: 'Aluminum, wood, vinyl, chain-link — each has trade-offs.',
    multiSelect: false,
    options: [
      { value: 'decided_aluminum', label: 'Yes, decided on aluminum', points: 17 },
      { value: 'researched',       label: "I've researched a bit",    points: 8  },
      { value: 'starting',         label: 'Just starting',            points: 0  },
      { value: 'havent_thought',   label: "Haven't thought about it", points: 0  },
    ],
  },
  {
    id: 'q9',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Do you know the approximate linear footage you need?',
    hint: 'Even a rough number helps with accurate pricing.',
    multiSelect: false,
    options: [
      { value: 'measured',       label: "Yes, I've measured",         points: 17 },
      { value: 'rough_idea',     label: 'I have a rough idea',        points: 8  },
      { value: 'need_help',      label: 'I need help figuring it out', points: 0  },
      { value: 'havent_thought', label: "Haven't thought about it",    points: 0  },
    ],
  },
  {
    id: 'q10',
    block: 'scored',
    blockLabel: 'Project Readiness',
    question: 'Have you considered gate placement and access points?',
    hint: 'Gates affect layout, cost, and daily convenience.',
    multiSelect: false,
    options: [
      { value: 'know_where',    label: 'Yes, I know where I want them', points: 17 },
      { value: 'some_ideas',    label: 'I have some ideas',             points: 8  },
      { value: 'havent_thought', label: "Haven't thought about it",     points: 0  },
      { value: 'need_help',     label: 'I need help deciding',          points: 0  },
    ],
  },

  // ── Block 3: Qualifying (Q11-Q15) ─────────────────────────────────
  {
    id: 'q11',
    block: 'qualify',
    blockLabel: 'About You',
    question: 'Which best describes your situation?',
    hint: 'Helps us tailor recommendations.',
    multiSelect: false,
    options: [
      { value: 'first_time',       label: 'First-time fence buyer'       },
      { value: 'replacing',        label: 'Replacing an existing fence'  },
      { value: 'adding',           label: 'Adding to existing fencing'   },
      { value: 'new_construction', label: 'New construction project'     },
      { value: 'commercial_gov',   label: 'Commercial / Government'      },
    ],
  },
  {
    id: 'q12',
    block: 'qualify',
    blockLabel: 'About You',
    question: "What's the #1 outcome you want from this project?",
    hint: 'We all want it all — pick the top priority.',
    multiSelect: false,
    options: [
      { value: 'premium_lasting', label: 'A premium, long-lasting fence'   },
      { value: 'max_security',    label: 'Maximum security'                },
      { value: 'pool_compliance', label: 'Pool code compliance'            },
      { value: 'property_value',  label: 'Boost property value'            },
      { value: 'boundary',        label: 'Clear property boundary'         },
    ],
  },
  {
    id: 'q13',
    block: 'qualify',
    blockLabel: 'About You',
    question: "What's been the biggest challenge so far?",
    hint: 'This helps us address your real pain points.',
    multiSelect: false,
    options: [
      { value: 'cant_visualize', label: "Can't visualize the finished look"  },
      { value: 'overwhelmed',   label: 'Overwhelmed by options'              },
      { value: 'cost',          label: 'Understanding true cost'             },
      { value: 'dont_know',     label: "Don't know where to start"           },
      { value: 'trust',         label: 'Finding a trustworthy supplier'      },
    ],
  },
  {
    id: 'q14',
    block: 'qualify',
    blockLabel: 'About You',
    question: 'What kind of help would be most valuable?',
    hint: 'We can meet you where you are.',
    multiSelect: false,
    options: [
      { value: 'info_pricing',       label: 'Info & pricing to review myself'   },
      { value: 'design_myself',      label: 'A tool to design it myself'        },
      { value: 'expert_guidance',    label: 'Expert guidance along the way'     },
      { value: 'full_consultation',  label: 'Full consultation & design'        },
      { value: 'handle_everything',  label: 'Just handle everything for me'     },
    ],
  },
  {
    id: 'q15',
    block: 'qualify',
    blockLabel: 'About You',
    question: 'Anything else we should know about your project?',
    hint: 'Optional — share any details that might help us.',
    multiSelect: false,
    type: 'openText',
  },
];

export const TOTAL_QUESTIONS = QUESTIONS.length;
